/**
 * Each item a boss can drop
 */
export const bossLoot: Record<string, Array<string>> = {
  eranog: [
    "finger",
    "back",
    "legs",
    "chest",
    "head",
    "shoulder",
    "trinket",
    "main_hand",
  ],
  sennarth: ["back", "feet", "hands", "one_hand", "trinket", "waist"],
  the_primal_council: [
    "back",
    "chest",
    "finger",
    "head",
    "off_hand",
    "legs",
    "one_hand",
    "shoulder",
    "trinket",
    "main_hand",
    "waist",
    "wrist",
  ],
  terros: [
    "chest",
    "head",
    "neck",
    "one_hand",
    "shoulder",
    "trinket",
    "main_hand",
    "waist",
  ],
  dathea: ["trinket", "shoulder", "one_hand", "neck", "head", "feet", "chest"],
  kurog_grimtotem: [
    "feet",
    "hands",
    "off_hand",
    "one_hand",
    "trinket",
    "main_hand",
    "waist",
    "wrist",
  ],
  broodkeeper_diurna: [
    "finger",
    "hands",
    "legs",
    "one_hand",
    "off_hand",
    "trinket",
    "main_hand",
    "waist",
    "wrist",
  ],
  raszageth: [
    "feet",
    "hands",
    "legs",
    "one_hand",
    "main_hand",
    "trinket",
    "wrist",
  ],
};
